# Generated by Django 5.0 on 2024-02-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_geograpphy_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_affairs',
            name='ans_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='english_and_literature',
            name='ans_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gujarati_and_literature',
            name='ans_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='maths_and_reasoning',
            name='ans_description',
            field=models.TextField(max_length=1000),
        ),
    ]
