# Generated by Django 5.0 on 2024-10-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_current_affairs_ans_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Operator',
            fields=[
                ('current_affairs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.current_affairs')),
            ],
            bases=('myapp.current_affairs',),
        ),
    ]
