# Generated by Django 5.0 on 2024-12-15 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_general_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Affairs2',
            fields=[
                ('current_affairs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.current_affairs')),
            ],
            bases=('myapp.current_affairs',),
        ),
    ]
