# Generated by Django 5.1.4 on 2025-03-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_current_affairs2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Paper',
            fields=[
                ('current_affairs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.current_affairs')),
            ],
            bases=('myapp.current_affairs',),
        ),
    ]
